### login
# {
#   "fcm": {
#     "token": "fSkGfr1yfrCQPIgqJgexCR:APA91bGzMfcN2vExbKlwEbTz0gEIqwa_8xAgZx0xp_fmvghxwkvvpTHxAlTxYeeJ3qSIeQALcwZpQqz92z5xTfzGTl86jvF1zJ4qyzebu5H1b28nTn859XwjovX9NEshY1WLWwlUBbE3",
#     "device": "chrome os mac"
#   }
# }
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "id": "new.minji",
  "pwd": "000000"
}

### my info
GET {{host}}/api/v1/auth/my
Content-Type: application/json
Authorization: Bearer {{auth}}


### get user list (secure-list)
# GET {{host}}/api/v1/user/secure-list?name=김&team-name=1&page=2&size=10
GET {{host}}/api/v1/user/secure-list?sex=1
Content-Type: application/json
Authorization: Bearer {{auth}}

### update user (my) info
PATCH {{host}}/api/v1/user/my/20309ab8-df91-48bc-9276-4841ac0ec4cb
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "profileImg": "https://cdn.kysa.page/cdn.png",
  "coverImg": "https://cdn.kysa.page/cdn.png",
  "introduce": "안녕하세요. 반갑습니다."
}

### update user password
PUT {{host}}/api/v1/user/my/20309ab8-df91-48bc-9276-4841ac0ec4cb/pwd
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "oldPwd": "123456",
  "newPwd": "000000"
}

### create group
POST {{host}}/api/v1/group/new
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "groupName": "IT 개발자 그룹",
  "introduce": "프로그래밍 및 소프트웨어 엔지니어링에 관심있으신 모든 분들을 환영합니다!"
}

### get group list
#GET {{host}}/api/v1/group?name=테스트&page=1&size=10
GET {{host}}/api/v1/group
Content-Type: application/json

### get my group follow
GET {{host}}/api/v1/group/mylist
Content-Type: application/json
Authorization: Bearer {{auth}}

### update group list
PATCH {{host}}/api/v1/group/855f0097-911b-43b6-b5cb-75a38b69baf8
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "introduce": "공지 그룹입니다 수정되었습니다!"
}

### follow group
PUT {{host}}/api/v1/group/follow/650ee3c6-cdc8-4833-817f-a3d6f8a73c88
Content-Type: application/json
Authorization: Bearer {{auth}}

{}

### delete group
DELETE {{host}}/api/v1/group/855f0097-911b-43b6-b5cb-75a38b69baf8
Content-Type: application/json
Authorization: Bearer {{auth}}

{}

### list group feed
GET {{host}}/api/v1/post/feed/650ee3c6-cdc8-4833-817f-a3d6f8a73c88
Content-Type: application/json

### create post
POST {{host}}/api/v1/post/new
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "groupRef": "650ee3c6-cdc8-4833-817f-a3d6f8a73c88",
  "message": "두번째 포스트입니다.",
  "image": "https://cdn.kysa.page/cdn.png"
}

### get single post by id
GET {{host}}/api/v1/post/detail/1006
Content-Type: application/json

### update single post
PATCH {{host}}/api/v1/post/1005
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "message": "수정된 포스트입니다."
}

### create reply
POST {{host}}/api/v1/post/1006/reply/new
Content-Type: application/json
Authorization: Bearer {{auth2}}

{
  "message": "안녕하세요. 소통해요!"
}

### list reply by post id
GET {{host}}/api/v1/post/1006/reply
Content-Type: application/json

### create like
PUT {{host}}/api/v1/post/like/1006
Content-Type: application/json
Authorization: Bearer {{auth2}}

{}

### delete post
DELETE {{host}}/api/v1/post/1005/delete
Content-Type: application/json
Authorization: Bearer {{auth}}

{}

### delete reply
DELETE {{host}}/api/v1/post/1006/reply/7/delete
Content-Type: application/json
Authorization: Bearer {{auth2}}

{}

### list chat rooms
GET {{host}}/api/v1/chat/recent
Content-Type: application/json
Authorization: Bearer {{auth}}

### get room user
GET {{host}}/api/v1/chat/room/44049ebe-f231-4fb3-89b9-be1da53d7ce3/detail
Content-Type: application/json
Authorization: Bearer {{auth}}

### list chat history
GET {{host}}/api/v1/chat/history/16a9f327-38d1-4832-b109-dd32f85fd0ee?begin-id=2
Content-Type: application/json
Authorization: Bearer {{auth}}

### send express ticket
POST {{host}}/api/v1/chat/ticket/10003
Content-Type: application/json
Authorization: Bearer {{auth}}

{}

### get total unread count
GET {{host}}/api/v1/chat/unread
Content-Type: application/json
Authorization: Bearer {{auth}}

### mark as read
PUT {{host}}/api/v1/chat/read/138c7fa3-76a3-45de-9e51-5b00abca09b4
Content-Type: application/json
Authorization: Bearer {{auth}}

{}

### get ticket count today
GET {{host}}/api/v1/chat/ticket/count
Content-Type: application/json
Authorization: Bearer {{auth}}


